apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erpc.fullname" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "erpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "erpc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "erpc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            {{- if .Values.client.webSocketEnabled }}
            - name: ws
              containerPort: {{ .Values.service.wsPort }}
              protocol: TCP
            {{- end }}
            - name: discovery-tcp
              containerPort: {{ .Values.service.discoveryPort }}
              protocol: TCP
            - name: discovery-udp
              containerPort: {{ .Values.service.discoveryPort }}
              protocol: UDP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http /nethermind/
          #command: ["./Nethermind.Runner", "--help"]
          args: ["--config", {{ .Values.client.chain | quote }}]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: "nethermind/configs/{{ include "chain.configName" . }}"
            subPath: {{ include "chain.configName" . }}
          - name: config-volume
            mountPath: "nethermind/chainspec/{{ include "chain.specName" . }}"
            subPath: {{ include "chain.specName" . }}
          {{- if or .Values.snapshotUse.enabled .Values.existingClaim.enabled }}
          {{- if .Values.snapshotUse.enabled }}
          - mountPath: {{ include "pvc.dbMountPath" . | quote }}
            name: db-volume
            subPath: database/{{ .Values.client.chain }}
          {{- end }}
          {{- if .Values.existingClaim.enabled }}
          - mountPath: {{ .Values.existingClaim.mountPath | quote }}
            name: existingclaim
          {{- end }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "erpc.fullname" . }}-config
        {{- if or .Values.snapshotUse.enabled .Values.existingClaim.enabled }}
        {{- if .Values.snapshotUse.enabled }}
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ include "erpc.PVCName" . }}
        {{- end }}
        {{- if .Values.existingClaim.enabled }}
        - name: existingclaim
          persistentVolumeClaim:
            claimName: {{ .Values.existingClaim.claimName | quote }}
        {{- end }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
