
{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "erpc.PVCName" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  accessModes:
    - {{ .Values.pvc.accessMode | quote }}
  resources:
    requests:
      {{- if .Values.snapshotUse.enabled }}
      storage: {{ .Values.snapshotUse.snapshotSize | quote }}
      {{- else }}
      storage: {{ .Values.pvc.volumeSize | quote }}
      {{- end }}
  {{- if .Values.snapshotUse.enabled }}
  dataSource:
    name: {{ include "erpc.volumeSnapshotName" . }}
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  {{- end }}
{{- end }}
