{{ $fullname :=  include "erpc.fullname" . }}
{{ $selectorLabels :=  include "erpc.selectorLabels" .  }}
{{ $serviceLabels :=  include "erpc.serviceLabels" .  }}
{{ $labels := include "erpc.labels" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
      {{- if and .Values.node.webSocketEnabled (not (.Values.didAuthProxy.enabled)) }}
    - port: {{ .Values.service.wsPort }}
      targetPort: {{ .Values.service.wsPort }}
      protocol: TCP
      name: ws
      {{- end }}
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p-tcp
    - port: {{ .Values.service.discoveryPort }}
      targetPort: {{ .Values.service.discoveryPort }}
      protocol: UDP
      name: discovery-udp
---
{{range $i := until (.Values.node.replicas | int) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}
  labels:
    {{- $serviceLabels | nindent 4 }}
    node: {{ $fullname }}-{{ $i }}
    instance: {{ $fullname }}-{{ $i }}
  annotations:
    {{- if eq $.Values.service.type "NodePort" }}
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: {{ $.Values.service.p2pPort | quote }}
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    {{- else }}
    {{- toYaml $.Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if eq $.Values.service.type "NodePort" }}
  type: NodePort
  externalTrafficPolicy: Local
  {{- else if eq $.Values.service.type "ClusterIP" }}
  type: ClusterIP
  clusterIP: None
  {{- end }}
  ports:
    {{- if not $.Values.didAuthProxy.enabled }}
    - port: {{ $.Values.service.httpPort }}
      targetPort: {{ $.Values.service.httpPort }}
      protocol: TCP
      name: http
      {{- if $.Values.node.webSocketEnabled }}
    - port: {{ $.Values.service.wsPort }}
      targetPort: {{ $.Values.service.wsPort }}
      protocol: TCP
      name: ws
      {{- end }}
    {{- end }}
    - port: {{ $.Values.service.p2pPort }}
      targetPort: {{ $.Values.service.p2pPort }}
      protocol: TCP
      name: p2p-tcp
    - port: {{ $.Values.service.discoveryPort }}
      targetPort: {{ $.Values.service.discoveryPort }}
      protocol: UDP
      name: discovery-udp
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
---
{{ end }}