apiVersion: v1
kind: Service
metadata:
  name: {{ include "erpc.fullname" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
      {{- if .Values.client.webSocketEnabled }}
    - port: {{ .Values.service.wsPort }}
      targetPort: {{ .Values.service.wsPort }}
      protocol: TCP
      name: ws
      {{- end }}
    - port: {{ .Values.service.discoveryPort }}
      targetPort: {{ .Values.service.discoveryPort }}
      protocol: TCP
      name: discovery-tcp
    - port: {{ .Values.service.discoveryPort }}
      targetPort: {{ .Values.service.discoveryPort }}
      protocol: UDP
      name: discovery-udp
  selector:
    {{- include "erpc.selectorLabels" . | nindent 4 }}
