{{ $fullname := include "erpc.fullname" . }}
{{ $labels := include "erpc.labels" . }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $fullname | quote }}
  labels:
    {{- $labels | nindent 4 }}
provisioner: ebs.csi.aws.com
parameters:
  type: "io1"
  iopsPerGB: "3"
  allowAutoIOPSPerGBIncrease: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
