{{- if .Values.node.volume.snapshot }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: {{ include "erpc.volumeSnapshotContentName" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
spec:
  volumeSnapshotRef:
    kind: VolumeSnapshot
    name: {{ include "erpc.volumeSnapshotName" . }}
    namespace: {{ .Release.Namespace }}
  source:
    snapshotHandle: {{ .Values.node.volume.snapshot }}
  driver: ebs.csi.aws.com
  deletionPolicy: Delete
  volumeSnapshotClassName: {{ include "erpc.volumeSnapshotClassName" . }}
{{- end }}